# Generated by Django 5.1.2 on 2024-10-22 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZKPRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_data', models.TextField()),
                ('proof_type', models.CharField(max_length=50)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ZKPSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_age_verification', models.BooleanField(default=True)),
                ('enable_identity_verification', models.BooleanField(default=True)),
                ('default_proof_type', models.CharField(default='standard', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zkp_settings_zeroknowledgeproof', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
