# Generated by Django 5.0.7 on 2024-10-26 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0002_customuser_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='did',
            field=models.CharField(blank=True, max_length=142),
        ),
    ]
