# Generated by Django 5.0.7 on 2024-10-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0003_customuser_did'),
        ('verification_service', '0002_alter_verificationrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verification_requests',
            field=models.ManyToManyField(blank=True, related_name='verified_users', to='verification_service.verificationrequest'),
        ),
    ]
