# Generated by Django 5.1.2 on 2024-10-22 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_type', models.CharField(max_length=100)),
                ('issuer', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Revoked', 'Revoked')], max_length=20)),
                ('expiry_date', models.DateField()),
                ('id_number', models.CharField(max_length=50, unique=True)),
                ('issued_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
